// <auto-generated />
using Lesson2EF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Lesson2EF.Migrations
{
    [DbContext(typeof(TeamManagmentDBContext))]
    [Migration("20210209121331_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Lesson2.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Email = "henk@breda.nl",
                            Name = "Henk",
                            TeamId = 201
                        },
                        new
                        {
                            Id = 1002,
                            Email = "loes@avans.nl",
                            Name = "Loes",
                            TeamId = 201
                        },
                        new
                        {
                            Id = 1003,
                            Email = "job@gmail.com",
                            Name = "Job",
                            TeamId = 202
                        });
                });

            modelBuilder.Entity("Lesson2.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 201,
                            Group = "Groep-1",
                            Title = "You snooze, you loose!"
                        },
                        new
                        {
                            Id = 202,
                            Group = "Groep-2",
                            Title = "Nachos"
                        },
                        new
                        {
                            Id = 203,
                            Group = "Groep-3",
                            Title = "3 front-end devs + 1 back-end dev"
                        },
                        new
                        {
                            Id = 204,
                            Group = "Groep-4",
                            Title = "Cinavas"
                        });
                });

            modelBuilder.Entity("Lesson2.Models.Member", b =>
                {
                    b.HasOne("Lesson2.Models.Team", "Team")
                        .WithMany("Enrolled")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Lesson2.Models.Team", b =>
                {
                    b.Navigation("Enrolled");
                });
#pragma warning restore 612, 618
        }
    }
}
